import { useState, useEffect, FormEvent } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  ShoppingBag, HelpCircle, ArrowRight, CheckCircle2, 
  Phone, Award, CheckCircle, Smartphone, Flame, LineChart, 
  ChevronRight, Users, Sparkles, ShieldCheck, RefreshCw, BarChart3
} from 'lucide-react';

interface EcommerceSeoPageProps {
  onBackToHome: () => void;
  openProposalForm: () => void;
}

export default function EcommerceSeoPage({ onBackToHome, openProposalForm }: EcommerceSeoPageProps) {
  useEffect(() => {
    const originalTitle = document.title;
    document.title = "Ecommerce SEO Services | Ecommerce SEO Agency | AKGLS Group";
    return () => {
      document.title = originalTitle;
    };
  }, []);

  const [monthlyTraffic, setMonthlyTraffic] = useState('25000');
  const [conversionRate, setConversionRate] = useState('1.8');
  const [aov, setAov] = useState('75');
  const [calcStatus, setCalcStatus] = useState<'idle' | 'calculating' | 'done'>('idle');
  
  const [projectedTraffic, setProjectedTraffic] = useState(0);
  const [revenueUplift, setRevenueUplift] = useState(0);
  const [additionalSales, setAdditionalSales] = useState(0);

  const [leadForm, setLeadForm] = useState({
    name: '',
    email: '',
    platform: 'Shopify',
    skuCount: '100-500'
  });
  const [leadSubmitted, setLeadSubmitted] = useState(false);
  const [activeFaq, setActiveFaq] = useState<number | null>(null);
  const [activeTab, setActiveTab] = useState<'products' | 'categories' | 'speed' | 'schema'>('products');
  const [schemaCopied, setSchemaCopied] = useState(false);

  const handleRevenueCalculate = (e: FormEvent) => {
    e.preventDefault();
    setCalcStatus('calculating');
    
    setTimeout(() => {
      const traffic = parseFloat(monthlyTraffic) || 0;
      const conv = parseFloat(conversionRate) / 100 || 0;
      const orderVal = parseFloat(aov) || 0;
      
      const currentRevenue = traffic * conv * orderVal;
      // Assume a conservative 45% uplift in search traffic, with a 15% optimization in conversion rate via UX-SEO improvements
      const newTraffic = Math.floor(traffic * 1.55);
      const newConv = conv * 1.15;
      const newRevenue = newTraffic * newConv * orderVal;

      setProjectedTraffic(newTraffic);
      setRevenueUplift(Math.floor(newRevenue - currentRevenue));
      setAdditionalSales(Math.floor((newRevenue - currentRevenue) / orderVal));
      setCalcStatus('done');
    }, 1000);
  };

  const handleLeadSubmit = (e: FormEvent) => {
    e.preventDefault();
    setLeadSubmitted(true);
  };

  const copySchemaMarkup = () => {
    const code = `{
  "@context": "https://schema.org",
  "@type": "Product",
  "name": "Target Product Sample",
  "image": "https://akglsgroup.com/product-image.png",
  "description": "High-intent ecommerce product optimization layout.",
  "brand": {
    "@type": "Brand",
    "name": "Client Brand"
  },
  "offers": {
    "@type": "Offer",
    "priceCurrency": "USD",
    "price": "49.99",
    "itemCondition": "https://schema.org/NewCondition",
    "availability": "https://schema.org/InStock"
  }
}`;
    navigator.clipboard.writeText(code);
    setSchemaCopied(true);
    setTimeout(() => setSchemaCopied(false), 2000);
  };

  const tabsContent = {
    products: {
      title: "Product Page SEO & Entity Mapping",
      icon: <ShoppingBag className="w-5 h-5 text-brand-indigo" />,
      desc: "Maximize search visibility for high-intent queries. We clean search elements, inject product specifications, organize image coordinates, and verify dynamic schema feeds.",
      bullets: [
        "Incorporate descriptive search modifiers inside Product H1 and title layouts",
        "Structure rich tables detailing product specifications, sizes, and compatibility codes",
        "Embed dynamic product rating and nested pricing schema markups",
        "Avoid template thin content flags by generating contextual product reviews"
      ]
    },
    categories: {
      title: "Commercial Category Page Authority",
      icon: <BarChart3 className="w-5 h-5 text-brand-purple" />,
      desc: "Category pages are high-value organic query hubs. We configure proper pagination, customize descriptive intro segments, and build logical cross-links to capture general queries.",
      bullets: [
        "Audit duplicate content generated by overlapping tag groupings",
        "Formulate descriptive header modules describing categorization scopes",
        "Integrate filter parameter blocking via canonical configurations",
        "Distribute inner link weight contextually from parent pages down to high-margin columns"
      ]
    },
    speed: {
      title: "UX, Page Speed & Conversion Optimization",
      icon: <Flame className="w-5 h-5 text-brand-teal" />,
      desc: "Fast load speed affects bounce statistics and customer checkouts. We streamline heavy asset files, bundle core scripting arrays, and compress large scale image payloads.",
      bullets: [
        "Audit Core Web Vitals (LCP, FID, CLS) across checkout templates",
        "Integrate dynamic lazy-loading sequences for below-fold media assets",
        "Streamline heavy checkout configurations to reduce transaction friction",
        "Synchronize fast cache delivery policies targeting cloud networks"
      ]
    },
    schema: {
      title: "Merchant Center & Product Feeds Integration",
      icon: <CheckCircle className="w-5 h-5 text-brand-orange" />,
      desc: "Expose product catalog directly to search systems. We configure XML feeds, link inventory changes, and resolve Merchant Center diagnostic anomalies.",
      bullets: [
        "Format product feeds aligning to Google Merchant technical guidelines",
        "Integrate auto-updating stock availability indicators in search structures",
        "Repair structural missing values, invalid product attributes, and currency codes",
        "Secure priority rich elements matching high-intent organic list tables"
      ]
    }
  };

  const FAQ_DATA = [
    {
      q: "How does Ecommerce SEO differ from general corporate SEO?",
      a: "Ecommerce SEO is transactional. It focuses heavily on product page technical configurations, dynamic pricing updates, complex facet catalog search filters, taxonomy schema structures, and fast load speeds to minimize cart abandonment."
    },
    {
      q: "Does your strategy handle platforms like Shopify or WooCommerce?",
      a: "Yes! We specialize in the backend architectures of Shopify, WooCommerce, Magento (Adobe Commerce), and custom headless frameworks."
    },
    {
      q: "What is your approach to handling out-of-stock product pages?",
      a: "We maintain established SEO rank value by keeping high-rank pages active with cross-sell recommendation widgets rather than throwing cold 404 errors."
    }
  ];

  return (
    <div className="pt-8">
      <section className="relative overflow-hidden py-16 lg:py-24 border-b border-slate-850">
        <div className="absolute inset-0 bg-gradient-to-b from-brand-indigo/10 via-transparent to-transparent pointer-events-none" />
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
            
            <div className="lg:col-span-7 space-y-6 text-left">
              <div className="inline-flex items-center gap-2 px-3 py-1 bg-brand-indigo/10 text-brand-indigo rounded-full text-xs font-extrabold uppercase tracking-widest">
                <ShoppingBag className="w-3.5 h-3.5" /> High-conversion Digital Shelf
              </div>
              <h1 className="text-3xl sm:text-5xl font-black text-white tracking-tight leading-tight font-display">
                Ecommerce SEO Services & <span className="text-transparent bg-clip-text bg-gradient-to-r from-brand-indigo to-brand-purple">Organic Transaction Growth</span>
              </h1>
              <p className="text-slate-350 text-base sm:text-lg leading-relaxed max-w-2xl">
                Increase product page footprint, capture high-purchase intent traffic parameters, and optimize transaction channels. Secure sustainable sales volumes.
              </p>

              <div className="grid grid-cols-3 gap-4 border-t border-slate-850 pt-8 mt-6 font-mono">
                <div>
                  <p className="text-xl sm:text-2xl font-black text-white">+55%</p>
                  <p className="text-[10px] text-slate-400 font-extrabold uppercase tracking-wider mt-1">Average Traffic Lift</p>
                </div>
                <div>
                  <p className="text-xl sm:text-2xl font-black text-brand-teal">+15%</p>
                  <p className="text-[10px] text-slate-400 font-extrabold uppercase tracking-wider mt-1">Conversion Lift</p>
                </div>
                <div>
                  <p className="text-xl sm:text-2xl font-black text-brand-purple">Real-Time</p>
                  <p className="text-[10px] text-slate-400 font-extrabold uppercase tracking-wider mt-1">Product Feed Sync</p>
                </div>
              </div>
            </div>

            {/* Right Merchant Growth Estimation Tool */}
            <div className="lg:col-span-5">
              <div className="bg-[#0c1221] border border-slate-800 rounded-2xl p-6 shadow-2xl relative">
                <div className="absolute top-0 right-4 -translate-y-1/2">
                  <span className="bg-brand-teal/10 text-brand-teal text-[9px] font-black uppercase tracking-widest px-2.5 py-1 rounded-full border border-brand-teal/20">
                    Organic Sales Calculator
                  </span>
                </div>
                <h3 className="text-base font-black text-white mb-2 flex items-center gap-2 text-left">
                  <LineChart className="w-5 h-5 text-brand-indigo" /> Estimate Your Revenue Uplifts
                </h3>
                <p className="text-xs text-slate-403 mb-6 text-left">
                  Model your current metrics to see how localized authority gains affect raw purchase rates.
                </p>

                <form onSubmit={handleRevenueCalculate} className="space-y-4 text-left">
                  <div className="space-y-1">
                    <label className="text-[9px] text-slate-400 font-bold uppercase tracking-wider">Avg. Monthly Organic Traffic</label>
                    <input 
                      type="number" 
                      required
                      value={monthlyTraffic}
                      onChange={(e) => setMonthlyTraffic(e.target.value)}
                      className="w-full bg-slate-950 border border-slate-850 focus:border-brand-indigo rounded-xl py-2.5 px-3.5 text-xs text-white font-mono outline-none"
                    />
                  </div>

                  <div className="grid grid-cols-2 gap-3">
                    <div className="space-y-1">
                      <label className="text-[9px] text-slate-400 font-bold uppercase tracking-wider">Conversion Rate (%)</label>
                      <input 
                        type="number" 
                        required
                        step="0.1"
                        value={conversionRate}
                        onChange={(e) => setConversionRate(e.target.value)}
                        className="w-full bg-slate-950 border border-slate-850 focus:border-brand-indigo rounded-xl py-2.5 px-3.5 text-xs text-white font-mono outline-none"
                      />
                    </div>
                    <div className="space-y-1">
                      <label className="text-[9px] text-slate-400 font-bold uppercase tracking-wider">Average Order Value ($)</label>
                      <input 
                        type="number" 
                        required
                        value={aov}
                        onChange={(e) => setAov(e.target.value)}
                        className="w-full bg-slate-950 border border-slate-850 focus:border-brand-indigo rounded-xl py-2.5 px-3.5 text-xs text-white font-mono outline-none"
                      />
                    </div>
                  </div>

                  <button 
                    type="submit"
                    className="w-full bg-brand-indigo hover:bg-opacity-95 text-white text-xs font-black uppercase tracking-wider py-3.5 rounded-xl transition-all"
                  >
                    {calcStatus === 'calculating' ? 'Processing Product Metrics...' : 'Calculate Monthly Growth'}
                  </button>
                </form>

                <AnimatePresence mode="wait">
                  {calcStatus === 'done' && (
                    <motion.div 
                      initial={{ opacity: 0, scale: 0.95 }}
                      animate={{ opacity: 1, scale: 1 }}
                      className="mt-6 p-4 bg-slate-950 rounded-xl border border-slate-850 text-left font-mono space-y-3 text-xs"
                    >
                      <div className="flex justify-between border-b border-slate-850 pb-2.5">
                        <span className="text-slate-400">PROJECTED TRAFFIC:</span>
                        <span className="text-white font-bold">{projectedTraffic} sessions / mo</span>
                      </div>
                      <div className="flex justify-between border-b border-slate-850 pb-2.5">
                        <span className="text-slate-400 font-extrabold uppercase">ADDITIONAL REVENUE:</span>
                        <span className="text-brand-teal font-black text-sm">+${revenueUplift.toLocaleString()} USD / mo</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-slate-400">EXTRA SALES ORDERS:</span>
                        <span className="text-brand-purple font-bold">+{additionalSales} orders / mo</span>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            </div>

          </div>
        </div>
      </section>

      {/* Tabs */}
      <section className="py-20 border-b border-slate-850 bg-slate-950/20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-3xl mx-auto mb-16 space-y-4">
            <h2 className="text-2xl sm:text-4xl font-black text-white tracking-tight font-display">
              Four Pillars of Ecommerce SEO Reach
            </h2>
          </div>

          <div className="flex flex-wrap items-center justify-center gap-2 mb-10">
            {Object.keys(tabsContent).map((key) => {
              const tab = tabsContent[key as keyof typeof tabsContent];
              const isSelected = activeTab === key;
              return (
                <button
                  key={key}
                  onClick={() => setActiveTab(key as any)}
                  className={`px-5 py-3 rounded-xl text-xs font-bold uppercase tracking-wider transition-all flex items-center gap-2 ${
                    isSelected 
                      ? 'bg-brand-indigo text-white shadow-md' 
                      : 'bg-slate-900 text-slate-400 border border-slate-800 hover:text-white'
                  }`}
                >
                  {tab.icon}
                  <span>{tab.title}</span>
                </button>
              );
            })}
          </div>

          <AnimatePresence mode="wait">
            <motion.div
              key={activeTab}
              initial={{ opacity: 0, y: 15 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              className="bg-[#0c1221] border border-slate-800 rounded-2xl p-6 sm:p-10 text-left max-w-4xl mx-auto"
            >
              <div className="grid grid-cols-1 md:grid-cols-12 gap-8 items-start">
                <div className="md:col-span-8 space-y-5">
                  <h3 className="text-xl font-black text-white font-display">
                    {tabsContent[activeTab].title}
                  </h3>
                  <p className="text-slate-305 text-sm sm:text-base leading-relaxed">
                    {tabsContent[activeTab].desc}
                  </p>
                  <div className="space-y-2.5 pt-2">
                    {tabsContent[activeTab].bullets.map((bullet, idx) => (
                      <div key={idx} className="flex items-start gap-2">
                        <CheckCircle2 className="w-5 h-5 text-brand-emerald shrink-0 mt-0.5" />
                        <span className="text-xs sm:text-sm text-slate-300">{bullet}</span>
                      </div>
                    ))}
                  </div>
                </div>

                <div className="md:col-span-4 bg-slate-950 p-6 rounded-xl border border-slate-850 text-center space-y-4">
                  <div>
                    <span className="text-[10px] font-mono text-slate-500 block uppercase tracking-wider">TYPICAL BOUNCE DECAY</span>
                    <span className="text-3xl font-black text-brand-teal font-mono">-24%</span>
                  </div>
                  <button 
                    onClick={openProposalForm}
                    className="w-full bg-brand-indigo hover:bg-opacity-95 text-white font-bold text-[11px] uppercase tracking-wider py-3 rounded-lg shadow"
                  >
                    Optimize Checkout Linkages
                  </button>
                </div>
              </div>
            </motion.div>
          </AnimatePresence>
        </div>
      </section>

      {/* Schema Block */}
      <section className="py-20 border-b border-slate-850">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
            
            <div className="lg:col-span-5 text-left space-y-5">
              <span className="text-[11px] text-brand-purple font-black uppercase tracking-widest font-mono">PRODUCT SCHEMA</span>
              <h2 className="text-2xl sm:text-4xl font-black text-white tracking-tight font-display">
                Expose Star Ratings In Search Lists
              </h2>
              <p className="text-slate-300 text-xs sm:text-sm leading-relaxed">
                Our dynamic schema generators inject ratings, dynamic pricing variables, and live stock statuses directly into the markup. This allows Google to generate product listing snippets instantly.
              </p>
              <button 
                onClick={copySchemaMarkup}
                className={`px-5 py-3 rounded-xl font-bold uppercase text-[11px] tracking-wider transition-all flex items-center gap-2 ${
                  schemaCopied ? 'bg-brand-emerald text-white' : 'bg-brand-purple hover:bg-opacity-95 text-white'
                }`}
              >
                {schemaCopied ? 'Product Schema Copied!' : 'Copy Schema Code Template'}
              </button>
            </div>

            <div className="lg:col-span-7 font-mono">
              <div className="bg-slate-950 border border-slate-850 rounded-2xl overflow-hidden shadow-2xl">
                <div className="bg-[#0b101b] py-2.5 px-4 border-b border-slate-850 flex items-center justify-between">
                  <span className="text-[10px] text-slate-400">ecommerce-product-schema.json</span>
                </div>
                <pre className="p-4 text-left text-[11px] text-brand-teal/90 overflow-x-auto leading-relaxed">
{`{
  "@context": "https://schema.org/",
  "@type": "Product",
  "name": "Target Product Descriptor",
  "offers": {
    "@type": "AggregateOffer",
    "lowPrice": "19.99",
    "highPrice": "49.99",
    "priceCurrency": "USD",
    "offerCount": "8"
  }
}`}
                </pre>
              </div>
            </div>

          </div>
        </div>
      </section>

      {/* FAQs */}
      <section className="py-20 border-b border-slate-850 bg-slate-950/10">
        <div className="max-w-4xl mx-auto px-4 sm:px-6">
          <div className="text-center mb-16 space-y-4">
            <h2 className="text-2xl sm:text-4xl font-black text-white tracking-tight font-display">
              Frequently Asked Questions
            </h2>
          </div>

          <div className="space-y-4">
            {FAQ_DATA.map((item, idx) => {
              const isOpen = activeFaq === idx;
              return (
                <div key={idx} className="bg-[#0c1221] border border-slate-800 rounded-xl overflow-hidden">
                  <button
                    onClick={() => setActiveFaq(isOpen ? null : idx)}
                    className="w-full text-left py-4 px-6 flex items-center justify-between font-bold text-white text-[13px] sm:text-sm"
                  >
                    <span>{item.q}</span>
                    <ChevronRight className={`w-4 h-4 text-slate-500 transition-transform ${isOpen ? 'rotate-90 text-brand-indigo' : ''}`} />
                  </button>
                  <AnimatePresence>
                    {isOpen && (
                      <motion.div
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: "auto", opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        className="border-t border-slate-850 px-6 py-4 text-xs sm:text-sm text-slate-355 leading-relaxed text-left"
                      >
                        {item.a}
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* CTA section */}
      <section id="ecommerce-cta" className="py-20 bg-gradient-to-t from-slate-950 to-transparent">
        <div className="max-w-4xl mx-auto px-4 sm:px-6">
          <div className="bg-gradient-to-tr from-[#090b14] via-[#0e162d] to-[#0a0f1d] border border-slate-800 rounded-3xl p-6 sm:p-10 text-center relative overflow-hidden shadow-2xl">
            <div className="absolute top-0 left-0 w-full h-[3px] bg-gradient-to-r from-brand-indigo via-brand-purple to-brand-teal" />
            <h3 className="text-2xl sm:text-4xl font-black text-white font-display tracking-tight mb-4">
              Ignite Your Organic Transactions
            </h3>
            <p className="text-slate-300 text-xs sm:text-sm max-w-xl mx-auto mb-8">
              Submit your merchant information. We will run competitor SKU analysis, catalog gaps, and layout a high-margin internal linking roadmap to capture organic checkout opportunities.
            </p>

            {leadSubmitted ? (
              <div className="bg-brand-emerald/10 border border-brand-emerald/20 text-emerald-300 py-6 px-4 rounded-2xl max-w-lg mx-auto">
                <p className="text-sm font-black uppercase">Merchant Audit Scheduled</p>
                <p className="text-xs text-slate-400 mt-1">Our lead retail growth analyst will share your structural taxonomy review inside 24 hours.</p>
              </div>
            ) : (
              <form onSubmit={handleLeadSubmit} className="space-y-4 max-w-lg mx-auto text-left">
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <input 
                    type="text" 
                    required
                    placeholder="Merchant Full Name"
                    value={leadForm.name}
                    onChange={(e) => setLeadForm(prev => ({ ...prev, name: e.target.value }))}
                    className="bg-slate-950 border border-slate-850 rounded-xl py-3 px-4 text-xs text-white placeholder-slate-500 outline-none"
                  />
                  <input 
                    type="email" 
                    required
                    placeholder="Email Address"
                    value={leadForm.email}
                    onChange={(e) => setLeadForm(prev => ({ ...prev, email: e.target.value }))}
                    className="bg-slate-950 border border-slate-850 rounded-xl py-3 px-4 text-xs text-white placeholder-slate-500 outline-none"
                  />
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-1">
                    <label className="text-[10px] text-slate-400 font-extrabold uppercase">Platform</label>
                    <select
                      value={leadForm.platform}
                      onChange={(e) => setLeadForm(prev => ({ ...prev, platform: e.target.value }))}
                      className="w-full bg-slate-950 border border-slate-850 rounded-xl py-3 px-4 text-xs text-white font-semibold outline-none"
                    >
                      <option value="Shopify">Shopify</option>
                      <option value="WooCommerce">WooCommerce</option>
                      <option value="Magento">Magento / Headless</option>
                    </select>
                  </div>
                  <div className="space-y-1">
                    <label className="text-[10px] text-slate-400 font-extrabold uppercase">SKU Count</label>
                    <select
                      value={leadForm.skuCount}
                      onChange={(e) => setLeadForm(prev => ({ ...prev, skuCount: e.target.value }))}
                      className="w-full bg-slate-950 border border-slate-850 rounded-xl py-3 px-4 text-xs text-white font-semibold outline-none"
                    >
                      <option value="100-500">100 - 500 SKUs</option>
                      <option value="500-5000">500 - 5,000 SKUs</option>
                      <option value="5000+">5,000+ SKUs</option>
                    </select>
                  </div>
                </div>
                <button 
                  type="submit"
                  className="w-full bg-gradient-to-r from-brand-indigo to-brand-purple text-white font-bold text-xs uppercase tracking-wider py-4 rounded-xl shadow"
                >
                  Generate Free Product-Category Audit
                </button>
              </form>
            )}
          </div>
        </div>
      </section>
    </div>
  );
}
