import { CrmClient, CrmTeamMember, CrmCommunication } from './types/crm';

export const INITIAL_CRM_TEAM: CrmTeamMember[] = [
  {
    id: 'team-1',
    name: 'Amrish Singh',
    email: 'amrish@akglsgroup.com',
    phone: '+91 831 811 4492',
    role: 'Founder & Technical Director',
    type: 'Internal Employee',
    status: 'Active',
    assignedClientsCount: 3,
    specialties: ['Technical SEO', 'AI Engine Optimization', 'Web Architecture', 'Enterprise Growth'],
    joinDate: 'Jan 2023',
    notes: 'Oversees core technical accounts and high-ticket enterprise contracts.'
  },
  {
    id: 'team-2',
    name: 'Priya Sharma',
    email: 'priya.s@akglsgroup.com',
    phone: '+91 98210 55432',
    role: 'Senior SEO & GEO Specialist',
    type: 'Internal Employee',
    status: 'Active',
    assignedClientsCount: 4,
    specialties: ['Generative Engine Optimization (GEO)', 'On-Page SEO', 'Schema Markup', 'Citation Audits'],
    joinDate: 'Mar 2024',
    notes: 'Handles AI search visibility, schema architecture, and editorial workflows.'
  },
  {
    id: 'team-3',
    name: 'Amit Patel',
    email: 'amit.web@akglsgroup.com',
    phone: '+91 97123 44890',
    role: 'Lead Full-Stack Developer',
    type: 'Internal Employee',
    status: 'Active',
    assignedClientsCount: 3,
    specialties: ['React / Vite', 'Shopify Liquid', 'WordPress / WooCommerce', 'Core Web Vitals'],
    joinDate: 'Jul 2024',
    notes: 'Develops client web portals, Shopify stores, and speed optimization overhauls.'
  },
  {
    id: 'team-4',
    name: 'Rahul Verma',
    email: 'rahul.v@akglspartners.com',
    phone: '+91 98901 23456',
    role: 'PPC & Local Search Associate',
    type: 'Agent / Associate',
    status: 'Active',
    assignedClientsCount: 2,
    specialties: ['Google Ads Search', 'Performance Max', 'Google Business Profile', 'Local Citations'],
    joinDate: 'Oct 2024',
    notes: 'Partner associate managing regional service businesses and clinics.'
  },
  {
    id: 'team-5',
    name: 'Neha Kapoor',
    email: 'neha.ads@akglspartners.com',
    phone: '+91 98109 87612',
    role: 'Paid Social & Creative Lead',
    type: 'Agent / Associate',
    status: 'Active',
    assignedClientsCount: 3,
    specialties: ['Meta Ads Manager', 'Instagram Reels Retargeting', 'Creative Ad Copy', 'Landing Page CRO'],
    joinDate: 'Jan 2025',
    notes: 'Specializes in high-ROI Meta ad funnels for real estate and ecommerce brands.'
  },
  {
    id: 'team-6',
    name: 'David Miller',
    email: 'david.copy@freelance-akgls.net',
    phone: '+1 415 620 9941',
    role: 'Content Strategist & Copywriter',
    type: 'Freelance Consultant',
    status: 'Active',
    assignedClientsCount: 2,
    specialties: ['B2B SaaS Content', 'Technical Whitepapers', 'Answer Engine Optimization', 'Press Releases'],
    joinDate: 'Feb 2025',
    notes: 'US-based remote freelance copywriter for international English enterprise content.'
  },
  {
    id: 'team-7',
    name: 'Vikram Joshi',
    email: 'vikram.j@akglsgroup.com',
    phone: '+91 88001 99221',
    role: 'Client Success & Outreach Agent',
    type: 'Agent / Associate',
    status: 'Active',
    assignedClientsCount: 2,
    specialties: ['Client Onboarding', 'Contract Renewals', 'WhatsApp Inbound', 'Cold Outreach'],
    joinDate: 'Nov 2024',
    notes: 'Handles client communication logging, proposal follow-ups, and weekly check-ins.'
  }
];

export const INITIAL_CRM_CLIENTS: CrmClient[] = [
  {
    id: 'client-apex-apparel',
    companyName: 'Apex Shopify Wear',
    contactPerson: 'Sarah Jenkins',
    email: 'sarah@apexapparel.store',
    phone: '+1 (415) 890-2341',
    websiteUrl: 'https://apexapparel.store',
    industry: 'Ecommerce Fashion & Apparel',
    status: 'Active',
    assignedTeamMemberId: 'team-1',
    assignedTeamMemberName: 'Amrish Singh',
    totalMonthlyRetainer: 5200,
    currency: 'USD',
    contractStartDate: '2025-11-01',
    notes: 'High-growth direct-to-consumer apparel store. Primary focus is reducing customer acquisition cost and scaling SEO visibility in ChatGPT & Perplexity.',
    createdAt: '2025-11-01T10:00:00.000Z',
    updatedAt: '2026-03-15T14:30:00.000Z',
    servicesTaken: [
      {
        id: 'srv-apex-1',
        name: 'Shopify Store Development & CRO',
        category: 'webdev',
        status: 'Active',
        pricingModel: 'Monthly Retainer',
        budgetOrFee: 2200,
        currency: 'USD',
        startDate: '2025-11-01',
        renewalDate: '2026-11-01',
        deliverablesSummary: 'Speed optimization, PDP checkout improvements, A/B testing variations, mobile UX overhaul.',
        progressPercentage: 88
      },
      {
        id: 'srv-apex-2',
        name: 'Google Ads & Performance Max Management',
        category: 'ppc',
        status: 'Active',
        pricingModel: 'Monthly Retainer',
        budgetOrFee: 1800,
        currency: 'USD',
        startDate: '2025-12-01',
        renewalDate: '2026-12-01',
        deliverablesSummary: 'Shopping feed management, negative keyword pruning, ROAS target 4.2x maintenance.',
        progressPercentage: 92
      },
      {
        id: 'srv-apex-3',
        name: 'Technical SEO & Generative Engine Optimization',
        category: 'aiseo',
        status: 'Active',
        pricingModel: 'Monthly Retainer',
        budgetOrFee: 1200,
        currency: 'USD',
        startDate: '2025-11-01',
        renewalDate: '2026-11-01',
        deliverablesSummary: 'Structured data schemas for apparel products, citation indexing across Perplexity and Gemini.',
        progressPercentage: 75
      }
    ]
  },
  {
    id: 'client-fintech-velocity',
    companyName: 'Fintech Velocity Corp',
    contactPerson: 'Marcus Vance',
    email: 'm.vance@fintechvelocity.io',
    phone: '+1 (212) 670-8819',
    websiteUrl: 'https://fintechvelocity.io',
    industry: 'Financial Technology & B2B SaaS',
    status: 'Active',
    assignedTeamMemberId: 'team-2',
    assignedTeamMemberName: 'Priya Sharma',
    totalMonthlyRetainer: 7000,
    currency: 'USD',
    contractStartDate: '2025-10-15',
    notes: 'Series B FinTech platform. Target is dominating organic search keywords for enterprise CFO software and banking APIs.',
    createdAt: '2025-10-15T09:00:00.000Z',
    updatedAt: '2026-03-20T11:00:00.000Z',
    servicesTaken: [
      {
        id: 'srv-fin-1',
        name: 'Enterprise SEO & GEO Roadmap',
        category: 'seo',
        status: 'Active',
        pricingModel: 'Monthly Retainer',
        budgetOrFee: 3500,
        currency: 'USD',
        startDate: '2025-10-15',
        renewalDate: '2026-10-15',
        deliverablesSummary: 'Entity-first knowledge graph architecture, 40+ competitor cluster audits, Core Web Vitals maintenance.',
        progressPercentage: 85
      },
      {
        id: 'srv-fin-2',
        name: 'LinkedIn B2B Sponsored Content & Lead Ads',
        category: 'ppc',
        status: 'Active',
        pricingModel: 'Monthly Retainer',
        budgetOrFee: 2000,
        currency: 'USD',
        startDate: '2025-11-15',
        renewalDate: '2026-11-15',
        deliverablesSummary: 'Targeting enterprise VP Finance and FinTech engineering leads with gated research assets.',
        progressPercentage: 80
      },
      {
        id: 'srv-fin-3',
        name: 'Technical Thought Leadership Content',
        category: 'content',
        status: 'In Progress',
        pricingModel: 'Monthly Retainer',
        budgetOrFee: 1500,
        currency: 'USD',
        startDate: '2026-01-05',
        renewalDate: '2026-10-15',
        deliverablesSummary: '4 in-depth monthly whitepapers and developer API integration tutorials written by David Miller.',
        progressPercentage: 65
      }
    ]
  },
  {
    id: 'client-apex-dental',
    companyName: 'Apex Dental Care & Implant Center',
    contactPerson: 'Dr. Rohit Verma',
    email: 'dr.rohit@apexdental.in',
    phone: '+91 98201 44521',
    websiteUrl: 'https://apexdentalcare.in',
    industry: 'Healthcare & Multispecialty Clinics',
    status: 'Active',
    assignedTeamMemberId: 'team-4',
    assignedTeamMemberName: 'Rahul Verma',
    totalMonthlyRetainer: 60000,
    currency: 'INR',
    contractStartDate: '2025-12-01',
    notes: 'Multi-chair dental clinic specializing in painless dental implants and smile makeovers in Delhi NCR.',
    createdAt: '2025-12-01T12:00:00.000Z',
    updatedAt: '2026-03-18T16:45:00.000Z',
    servicesTaken: [
      {
        id: 'srv-den-1',
        name: 'Local SEO & Google Business Profile 3-Pack Growth',
        category: 'seo',
        status: 'Active',
        pricingModel: 'Monthly Retainer',
        budgetOrFee: 35000,
        currency: 'INR',
        startDate: '2025-12-01',
        renewalDate: '2026-12-01',
        deliverablesSummary: 'Hyper-local citation building, weekly geotagged updates, automated patient review acquisition.',
        progressPercentage: 90
      },
      {
        id: 'srv-den-2',
        name: 'Google Call-Only Ads for Dental Emergencies & Implants',
        category: 'ppc',
        status: 'Active',
        pricingModel: 'Monthly Retainer',
        budgetOrFee: 25000,
        currency: 'INR',
        startDate: '2026-01-10',
        renewalDate: '2026-12-01',
        deliverablesSummary: 'Targeted radius ads generating direct phone bookings with sub-₹350 cost-per-lead.',
        progressPercentage: 82
      }
    ]
  },
  {
    id: 'client-precision-metal',
    companyName: 'Precision Metal Works Ltd',
    contactPerson: 'Vikramaditya Singhania',
    email: 'vikram@precisionmetal.co.in',
    phone: '+91 99100 87654',
    websiteUrl: 'https://precisionmetalworks.co.in',
    industry: 'Industrial Manufacturing & Global Exports',
    status: 'Active',
    assignedTeamMemberId: 'team-3',
    assignedTeamMemberName: 'Amit Patel',
    totalMonthlyRetainer: 55000,
    currency: 'INR',
    contractStartDate: '2026-01-10',
    notes: 'Precision automotive and aerospace CNC machined parts exporter to Germany and USA.',
    createdAt: '2026-01-10T11:00:00.000Z',
    updatedAt: '2026-03-21T09:15:00.000Z',
    servicesTaken: [
      {
        id: 'srv-pmw-1',
        name: 'Custom B2B Industrial Web Portal Redesign',
        category: 'webdev',
        status: 'In Progress',
        pricingModel: 'One-Time Project',
        budgetOrFee: 180000,
        currency: 'INR',
        startDate: '2026-01-10',
        renewalDate: '2026-04-15',
        deliverablesSummary: 'React + Node catalog with CAD spec downloads, RFQ quote generator, and CRM webhook integration.',
        progressPercentage: 70
      },
      {
        id: 'srv-pmw-2',
        name: 'Global B2B Export SEO & Multilingual GEO',
        category: 'seo',
        status: 'Active',
        pricingModel: 'Monthly Retainer',
        budgetOrFee: 55000,
        currency: 'INR',
        startDate: '2026-02-01',
        renewalDate: '2027-02-01',
        deliverablesSummary: 'Targeting overseas OEM procurement managers searching for custom CNC precision components.',
        progressPercentage: 60
      }
    ]
  },
  {
    id: 'client-skyline-realty',
    companyName: 'Skyline Real Estate Ventures',
    contactPerson: 'Ananya Roy',
    email: 'ananya@skylinerealty.com',
    phone: '+91 98112 33445',
    websiteUrl: 'https://skylinerealtyventures.com',
    industry: 'Real Estate & Luxury Apartments',
    status: 'Active',
    assignedTeamMemberId: 'team-5',
    assignedTeamMemberName: 'Neha Kapoor',
    totalMonthlyRetainer: 75000,
    currency: 'INR',
    contractStartDate: '2026-02-01',
    notes: 'Luxury golf villas and penthouse developer. Needs ultra-high-net-worth lead qualification via Instagram and Google Search.',
    createdAt: '2026-02-01T14:00:00.000Z',
    updatedAt: '2026-03-22T08:00:00.000Z',
    servicesTaken: [
      {
        id: 'srv-sky-1',
        name: 'Meta Ads & Instagram Video Lead Generation Funnel',
        category: 'ppc',
        status: 'Active',
        pricingModel: 'Monthly Retainer',
        budgetOrFee: 75000,
        currency: 'INR',
        startDate: '2026-02-01',
        renewalDate: '2026-08-01',
        deliverablesSummary: 'Cinematic walk-through video ads with instant WhatsApp CRM auto-responder qualification.',
        progressPercentage: 85
      },
      {
        id: 'srv-sky-2',
        name: 'Landing Page Speed & Mobile Conversion Optimization',
        category: 'webdev',
        status: 'Completed',
        pricingModel: 'One-Time Project',
        budgetOrFee: 40000,
        currency: 'INR',
        startDate: '2026-02-01',
        renewalDate: '2026-03-01',
        deliverablesSummary: 'Sub-1.2s mobile load time, interactive 3D floorplan previews, OTP lead validation.',
        progressPercentage: 100
      }
    ]
  },
  {
    id: 'client-zen-wellness',
    companyName: 'Zenith Organic Herbals',
    contactPerson: 'Karan Mehra',
    email: 'karan@zenithherbals.in',
    phone: '+91 97115 66778',
    websiteUrl: 'https://zenithherbals.in',
    industry: 'D2C Ayurveda & Organic Wellness',
    status: 'Onboarding',
    assignedTeamMemberId: 'team-7',
    assignedTeamMemberName: 'Vikram Joshi',
    totalMonthlyRetainer: 45000,
    currency: 'INR',
    contractStartDate: '2026-03-10',
    notes: 'New client onboarded for full digital growth stack: WordPress WooCommerce store overhaul and Amazon/Google ad synergy.',
    createdAt: '2026-03-10T16:00:00.000Z',
    updatedAt: '2026-03-21T18:00:00.000Z',
    servicesTaken: [
      {
        id: 'srv-zen-1',
        name: 'WordPress WooCommerce Speed & Security Overhaul',
        category: 'maintenance',
        status: 'In Progress',
        pricingModel: 'One-Time Project',
        budgetOrFee: 35000,
        currency: 'INR',
        startDate: '2026-03-10',
        renewalDate: '2026-04-10',
        deliverablesSummary: 'Migration to Cloudflare enterprise edge, checkout optimization, schema product feeds.',
        progressPercentage: 45
      },
      {
        id: 'srv-zen-2',
        name: 'Ayurvedic D2C SEO & Organic Keyword Clustering',
        category: 'seo',
        status: 'In Progress',
        pricingModel: 'Monthly Retainer',
        budgetOrFee: 45000,
        currency: 'INR',
        startDate: '2026-03-15',
        renewalDate: '2027-03-15',
        deliverablesSummary: 'Targeting non-branded organic searches for clean beauty and natural immunity supplements.',
        progressPercentage: 25
      }
    ]
  }
];

export const INITIAL_CRM_COMMUNICATIONS: CrmCommunication[] = [
  {
    id: 'comm-1',
    clientId: 'client-apex-apparel',
    clientName: 'Sarah Jenkins',
    companyName: 'Apex Shopify Wear',
    date: '2026-03-22T10:30:00.000Z',
    channel: 'Meeting',
    loggedByEmployeeId: 'team-1',
    loggedByEmployeeName: 'Amrish Singh',
    summary: 'Q1 Review & Summer Apparel Collection Campaign Strategy',
    discussionNotes: 'Reviewed ROAS from Google Shopping (sitting at 4.4x). Sarah approved increasing daily budget by 20% for the upcoming spring athletic line. Amit to deploy the revised PDP sticky add-to-cart by Thursday.',
    nextFollowUpDate: '2026-03-29',
    status: 'Resolved'
  },
  {
    id: 'comm-2',
    clientId: 'client-fintech-velocity',
    clientName: 'Marcus Vance',
    companyName: 'Fintech Velocity Corp',
    date: '2026-03-21T15:00:00.000Z',
    channel: 'Call',
    loggedByEmployeeId: 'team-2',
    loggedByEmployeeName: 'Priya Sharma',
    summary: 'GEO Perplexity Citation Spike & Whitepaper Deliverable',
    discussionNotes: 'Marcus confirmed seeing Fintech Velocity cited in Perplexity answers for "best corporate treasury API". Priya showed the entity graph markup roadmap. David Miller finishing draft 2 of the CFO Guide.',
    nextFollowUpDate: '2026-03-26',
    status: 'Follow-up Scheduled'
  },
  {
    id: 'comm-3',
    clientId: 'client-apex-dental',
    clientName: 'Dr. Rohit Verma',
    companyName: 'Apex Dental Care & Implant Center',
    date: '2026-03-20T12:15:00.000Z',
    channel: 'WhatsApp',
    loggedByEmployeeId: 'team-4',
    loggedByEmployeeName: 'Rahul Verma',
    summary: 'Lead Quality Feedback & Implant Consultations Booking',
    discussionNotes: 'Doctor shared WhatsApp message confirming 18 high-value implant consultations booked this month. Requested expanding Google Call ad radius from 8km to 14km around Noida clinic.',
    nextFollowUpDate: '2026-03-25',
    status: 'Action Required'
  },
  {
    id: 'comm-4',
    clientId: 'client-skyline-realty',
    clientName: 'Ananya Roy',
    companyName: 'Skyline Real Estate Ventures',
    date: '2026-03-19T14:40:00.000Z',
    channel: 'Meeting',
    loggedByEmployeeId: 'team-5',
    loggedByEmployeeName: 'Neha Kapoor',
    summary: 'Instagram Reel Creative Review & Site Visit Conversions',
    discussionNotes: 'Presented 3 new cinematic drone video ad variations for the Golf View penthouses. Ananya requested adding architect testimonial snippet in the first 3 seconds to boost hook rate.',
    nextFollowUpDate: '2026-03-24',
    status: 'Resolved'
  },
  {
    id: 'comm-5',
    clientId: 'client-precision-metal',
    clientName: 'Vikramaditya Singhania',
    companyName: 'Precision Metal Works Ltd',
    date: '2026-03-18T11:00:00.000Z',
    channel: 'Email',
    loggedByEmployeeId: 'team-3',
    loggedByEmployeeName: 'Amit Patel',
    summary: 'CAD Drawing Secure Download Portal Milestone Testing',
    discussionNotes: 'Sent staging link for the industrial catalog with encrypted RFQ form. Vikram requested NDA signature gating before European buyers can download proprietary STEP/IGES engineering files.',
    nextFollowUpDate: '2026-03-23',
    status: 'Follow-up Scheduled'
  },
  {
    id: 'comm-6',
    clientId: 'client-zen-wellness',
    clientName: 'Karan Mehra',
    companyName: 'Zenith Organic Herbals',
    date: '2026-03-17T16:20:00.000Z',
    channel: 'Call',
    loggedByEmployeeId: 'team-7',
    loggedByEmployeeName: 'Vikram Joshi',
    summary: 'Onboarding Checklist & Payment Gateway Integration',
    discussionNotes: 'Helped client setup Razorpay test keys and shared Google Search Console delegation request to priya.s@akglsgroup.com. Kickoff technical audit scheduled for next week.',
    nextFollowUpDate: '2026-03-24',
    status: 'Resolved'
  }
];
